name: Build (CLI)
on: workflow_dispatch

jobs:
  build-linux:
    name: Build (Linux)
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install zip
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: hello_world.py
          mode: standalone
      - name: Archive (bash)
        if: ${{ matrix.os != 'windows-latest' }}
        run: zip -r package.zip build/*
      - name: Archive (PowerShell)
        if: ${{ matrix.os == 'windows-latest' }}
        run: Compress-Archive -Path build/* -DestinationPath package.zip
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "package.zip"