name: Build (GUI)
on: workflow_dispatch

jobs:
  build-linux:
    name: Build
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Download icons
        uses: actions/checkout@v4
        with:
          repository: Silkbrush/assets
          path: assets
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install zip
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main_rewrite.py
          mode: app
          disable-cache: true
          macos-app-name: Zen Explorer
          enable-plugins: pyside6
          include-data-dir: explorer_ui/assets=explorer_ui/explorer_themes
          macos-app-icon: assets/app-icons/silkbrush-mac.icns
          windows-icon-from-ico: assets/app-icons/silkbrush-windows.ico
      - name: Rename (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mv build/main_rewrite.bin build/zen-explorer-gui
      - name: Rename (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: mv build/main_rewrite.app build/Zen\ Explorer.app
      - name: Rename (PowerShell)
        if: ${{ matrix.os == 'windows-latest' }}
        run: Rename-Item -Path build/main_rewrite.exe -NewName zen-explorer-gui.exe
      - name: Compress to ZIP (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: cd build; zip -r ../zen-explorer-gui.zip ./Zen\ Explorer.app
      - name: Upload package (Linux)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: zen-explorer-gui-linux
          path: build/zen-explorer-gui
      - name: Upload package (macOS)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: zen-explorer-gui-mac
          path: zen-explorer-gui.zip
      - name: Upload package (PowerShell)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: zen-explorer-gui-windows
          path: build/zen-explorer-gui.exe
